# Specific portal web deploy tasks 

- name: ensure cache and logs directories exists
  file:
    path: "/apps/dextra_reports/www/app/{{ item }}"
    state: directory
    mode: "0755"
  with_items:
    - cache
    - logs

- name: Set file access control to logs and cache directories
  command: "{{ item }}"
  with_items:
    - setfacl -R -m u:nginx:rwX -m u:webmaster:rwX /apps/dextra_reports/www/app/cache /apps/dextra_reports/www/app/logs
    - setfacl -dR -m u:nginx:rwX -m u:webmaster:rwX /apps/dextra_reports/www/app/cache /apps/dextra_reports/www/app/logs

- name: allow write permissions to cache directory through selinux context
  sefcontext:
    target: "/apps/dextra_reports/www/app/{{ item }}(/.*)?"
    setype: httpd_sys_script_rw_t
    state: present
  with_items:
    - cache
    - logs

- name: Apply new SELinux file context to cache and log directories
  command: "restorecon -R /apps/dextra_reports/www/app/{{ item }}"
  with_items:
    - cache
    - logs


  
