# Specific portal web deploy tasks 

- name: Syncronice files from prod to test
  shell: rsync -avzP -e 'ssh' fhernandez@11.0.10.5:/var/www/public/portal/web/ /apps/portal_crc/www/web
  become: webmaster
  delegate_to: "{% if env == 'test' %}vm-apps-crc{% elif env == 'prod' %}vm-app-paginaweb{% endif %}"
  loop: "{{ applications }}"
  when: 
    - deploy_app is defined
    - item.name == deploy_app

- name: Set file access control to logs and cache directories
  command: "{{ item }}"
  with_items:
    - setfacl -R -m u:nginx:rwX -m u:webmaster:rwX /apps/portal_crc/www/app/cache /apps/portal_crc/www/app/logs
    - setfacl -dR -m u:nginx:rwX -m u:webmaster:rwX /apps/portal_crc/www/app/cache /apps/portal_crc/www/app/logs

- name: allow write permissions to cache directory through selinux context
  sefcontext:
    target: "/apps/portal_crc/www/app/{{ item }}(/.*)?"
    setype: httpd_sys_script_rw_t
    state: present
  with_items:
    - cache
    - logs

- name: Apply new SELinux file context to cache and log directories
  command: "restorecon -R /apps/portal_crc/www/app/{{ item }}"
  with_items:
    - cache
    - logs
