- name: Copy Symfony config file
  template:
    src: symfony.2.parameters.yml.j2 
    dest: "{{ item.path }}/app/config/parameters.yml"
    owner: webmaster
    group: webmaster
    mode: '0644'
  with_items: "{{ applications }}"
  when: 
    - deploy_app is defined
    - item.type == type
    - item.name == deploy_app

- name: Set SELinux policy for the symfony site directory
  sefcontext:
    target: "{{ item.path }}(/.*)?"
    setype: httpd_sys_content_t
    state: present
  with_items: "{{ applications }}"
  when: 
    - deploy_app is defined
    - item.type == type
    - item.name == deploy_app

- name: Set SELinux policy for the Drupal site default folder
  sefcontext:
    target: "{{ item.path }}/web(/.*)?"
    setype: httpd_sys_rw_content_t
    state: present
  with_items: "{{ applications }}"
  when: 
    - deploy_app is defined
    - item.type == type
    - item.name == deploy_app
  
- name: Set SELinux policy for the symfony site content generated directory
  sefcontext:
    target: "{{ item.path }}/web/uploads(/.*)?"
    setype: httpd_sys_rw_content_t
    state: present
  with_items: "{{ applications }}"
  when: 
    - deploy_app is defined
    - item.type == type
    - item.name == deploy_app

- name: Set SElinux on all the site files
  command: restorecon -Rv {{ item.path }}
  with_items: "{{ applications }}"
  when: 
    - deploy_app is defined
    - item.type == type
    - item.name == deploy_app
