- name: Ensure if default directory exists
  file: 
    path: "{{ item.path }}/sites/default/files"
    state: directory
    owner: webmaster
    group: webmaster
    mode: '0775'
  with_items: "{{ applications }}"
  when:
   - deploy_app is defined
   - item.type == "drupal7" 
   - item.name == deploy_app

- name: debug item name
  debug:
    msg: item.name
  with_items: "{{ applications }}"
  when:
   - deploy_app is defined
   - item.type == "drupal7" 
   - item.name == deploy_app

- name: Copy Drupal config file
  template:
    src: drupal.7.settings.php.j2 
    dest: "{{ item.path }}/sites/default/settings.php"
    owner: webmaster
    group: webmaster
    mode: '0444'
  with_items: "{{ applications }}"
  when:
   - deploy_app is defined
   - item.type == "drupal7" 
   - item.name == deploy_app

- name: Set SELinux policy for the Drupal site directory
  sefcontext:
    target: "{{ item.path }}(/.*)?"
    setype: httpd_sys_content_t
    state: present
  with_items: "{{ applications }}"
  when:
   - deploy_app is defined
   - item.type == "drupal7" 
   - item.name == deploy_app

- name: Set SELinux policy for the Drupal site default folder
  sefcontext:
    target: "{{ item.path }}/sites/default(/.*)?"
    setype: httpd_sys_rw_content_t
    state: present
  with_items: "{{ applications }}"
  when:
   - deploy_app is defined
   - item.type == "drupal7" 
   - item.name == deploy_app
  
- name: Set SELinux policy for the Drupal site content generated directory
  sefcontext:
    target: "{{ item.path }}/sites/default/files(/.*)?"
    setype: httpd_sys_rw_content_t
    state: present
  with_items: "{{ applications }}"
  when:
   - deploy_app is defined
   - item.type == "drupal7" 
   - item.name == deploy_app

- name: Set SElinux on all the site files
  command: restorecon -Rv {{ item.path }}
  with_items: "{{ applications }}"
  when:
   - deploy_app is defined
   - item.type == "drupal7" 
   - item.name == deploy_app
