# Deploy tasks

- name: Debug vars
  debug:
    msg: "{{ applications }}"

- name:  Fetch source code from git
  git:
    repo: "{{ item.repository }}"
    dest: "{{ item.path }}"
    version: "{{ item.version }}"
  become: webmaster
  loop: "{{ applications }}"
  when: item.name in apps
