# Deploy tasks

- name: Debug vars
  debug:
    msg: "ops for {{ deploy_app }} in {{ applications }}"

- name:  Fetch source code from git
  git:
    repo: "{{ item.repository }}"
    dest: "{{ item.path }}"
    version: "{{ item.version }}"
  become: webmaster
  loop: "{{ applications }}"
  when: 
    - deploy_app is defined
    - item.name == deploy_app
