# Deploy tasks

- name:  Fetch source code from git
  git:
    repo: "{{ item.repository }}"
    dest: "{{ item.path }}"
    version: "{{ item.version }}"
  with_items: "{{ applications }}"
  become: webmaster
