
- name: Enable maintenance mode
  shell: |
    cd {{ item.path }}
    drush vset maintenance_mode 1
  with_items: "{{ applications }}"
  when: 
    - item.type == type
    - deploy_app is defined
  
- name: Run updates if available
  shell: |
    cd {{ item.path }}
    yes drush updatedb  
  with_items: "{{ applications }}"
  when: 
    - item.type == type
    - deploy_app is defined

- name: Exit from maintenance mode
  shell: |
    cd {{ item.path }}
    drush vset maintenance_mode 1
  with_items: "{{ applications }}"
  when: 
    - item.type == type
    - deploy_app is defined
