# Main tasks for app deployment

- include: deploy_site.yml
- include: config_drupal7_site.yml
  tags: [drupal7]
- include: drush_update.yml
  tags: [drush_update]
- include: config_symfony2_site.yml
  tags: [symfony2]
