
# These tasks are responsible to copy files to environments, starting 
# by test files or application code from version system.

- name: Create apps directory inside resources partition
  file:
    path: "/apps/{{ item.name }}/www"
    state: directory
    mode: '0755'
    owner: webmaster
    group: webmaster
  with_items: "{{ applications }}"

