- name: Install mariadb client to allow drush ops
  yum:
    name: mariadb
    state: present

- name: Ensure Drush is installed globally
  composer:
    command: require
    global_command: true
    arguments: "drush/drush:{{ drush_composer_version }}"
  register: drush_composer_require
  become: webmaster

