
- name: Ensure Drush is installed globally
  composer:
    command: require
    global_command: true
    arguments: "drush/drush:{{ drush_composer_version }}"
  register: drush_composer_require
  become: webmaster

