
- name: Install composer
  command: "{{ item }}"
  with_items:
    - cd /tmp
    - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
    - php -r "if (hash_file('sha384', 'composer-setup.php') === '"{{ composer_hash }}"') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
    - php composer-setup.php --install-dir=/usr/local/bin --filename=composer
    - php -r "unlink('composer-setup.php');"

- name: Ensure composer binaries are available in path env
  lineinfile:
    path: /etc/bashrc
    regexp: "^config/composer/vendor/bin"
    line: "export PATH=$HOME/.config/composer/vendor/bin:$PATH"

- name: Source /etc/bashrc file
  shell: source /etc/bashrc
