
- name: Configure timezone
  timezone:
    name: America/Bogota

- name: Install ntp
  yum: name=ntp state=present

- name: Ntp configuration
  template: src=ntp.conf.j2 dest=/etc/ntp.conf
  notify: restart ntp

- name: Start ntp service
  service: name=ntpd state=started enabled=yes
