---
# This playbook contains comon plays that will be run in all nodes

- name: Install common dependencies
  yum: name="{{ item }}" state=installed
  loop:
    - policycoreutils
    - policycoreutils-python
    - libselinux-python
    - libsemanage-python
    - firewalld

- name: Enable Remi release repo
  yum:
    name: https://rpms.remirepo.net/enterprise/remi-release-7.rpm
    state: present
  notify: yum-clean-metadata

- include: configure_ntp.yml
  tags: [ntp]
- include: configure_firewall.yml
