---
# Handle common notifications. This handler is called by other plays.

- name: restart ntp
  service: name=ntpd state=restarted

- name: yum-clean-metadata
  command: yum clean metadata
  args:
    warn: no
