
- name: Debug database connection params remember to source the database environment vars
  debug:
    msg: "dbname {{ item.dbname }} dbuser {{ item.dbuser }} upasswd {{ item.upasswd }}"
  loop: "{{ applications }}"
  when:
    - deploy_app is defined
    - item.name == deploy_app

- name: Create application database
  mysql_db: name={{ item.dbname }} state=present login_password={{ db_root_password }}
  loop: "{{ applications }}"
  when:
    - deploy_app is defined
    - item.name == deploy_app

- name: Create application database user
  mysql_user: name={{ item.dbuser }} password={{ item.upasswd }} priv='{{ item.dbname }}.*:ALL' state=present  host="%" login_password={{ db_root_password }}
  loop: "{{ applications }}"
  when:
    - deploy_app is defined
    - item.name == deploy_app

- name: Start MariaDB unit
  service: name=mariadb state=started enabled=yes
