# This playbook will install mariadb and configure database

- name: Install MariaDB package
  yum: name="{{ item }}" state=installed
  loop:
    - mariadb-server
    - MySQL-python

- name: Create Mysql configuration file
  template: src=my.cnf.j2 dest=/etc/my.cnf
  notify:
  - restart mariadb

- name: Create MariaDB log file
  file: path=/var/log/mysqld.log state=touch owner=mysql group=mysql mode=0775

- name: Create MariaDB PID directory
  file: path=/var/run/mysqld state=directory owner=mysql group=mysql mode=0775

- name: Create MariaDB Data directory
  file: path=/mnt/resource/mysql state=directory owner=mysql group=mysql mode=0775

- name: Insert firewall rule
  firewalld: port=3306/tcp permanent=true state=enabled immediate=yes

- name: Configure SElinux to allow mysql connections
  seboolean: name=mysql_connect_any state=true persistent=yes

- name: configure SElinux context to allow writable data directory
  sefcontext:
    target: '/mnt/resource/mysql(/.*)?'
    setype: mysqld_db_t
    state: present

- name: Apply new SELinux file context to filesystem
  command: restorecon -Rv /mnt/resource/mysql

- name: Debug database connection params - remember to source the database environment vars
  debug:
    msg: dbname {{ item.dbname }} dbuser {{ item.dbuser }} upasswd {{ item.upasswd }}
  with_items: "{{ applications }}"

- name: Create drupal database
  mysql_db: name={{ item.dbname}} state=present
  with_items: "{{ applications }}"

- name: Create drupal database user
  mysql_user: name={{ item.dbuser }} password={{ item.upasswd }} priv={{ item.dbname }}.*:ALL host='%' state=present
  with_items: "{{ applications }}"

- name: Start MariaDB unit
  service: name=mariadb state=started enabled=yes
