
- name: Set the root password 
  mysql_user: login_user=root name=root password="{{ db_root_password }}" state=present

- name: Secure the root user for IPV6 localhost (::1)
  mysql_user: login_user=root login_password="{{ db_root_password }}" user=root password="{{ db_root_password }}" host="::1"

- name: Secure the root user for IPV4 localhost (127.0.0.1)
  mysql_user: login_user=root login_password="{{ db_root_password }}" user=root password="{{ db_root_password }}" host="127.0.0.1"

- name: Secure the root user for localhost domain
  mysql_user: login_user=root login_password="{{ db_root_password }}" user=root password="{{ db_root_password }}" host="localhost"

- name: Secure the root user for server_hostname domain
  mysql_user: login_user=root login_password="{{ db_root_password }}" user=root password="{{ db_root_password }}" host="{{ ansible_fqdn }}"

- name: Deletes anonymous server user
  mysql_user: login_user=root login_password="{{ db_root_password }}" user="" host_all=yes state=absent

- name: Removes the test database
  mysql_db: login_user=root login_password="{{ db_root_password }}" db=test state=absent
