# Specific postdata deploy tasks

- name: Syncronice files from dev to postdata
  shell: "rsync -avzP -e 'ssh' {{ lookup('env', 'VM_ZOQUE_HOME') }}/Code/drupal/postdata/www/sites/default/files webmaster@52.170.254.161:/mnt/resources/webapps/postdata/sites/default"
  delegate_to: zoque
  become: snaphuman
  #synchronize: 
  #  src: "{{ lookup('env', 'VM_ZOQUE_HOME') }}/Code/drupal/postdata/www/sites/default/files/"
  #  dest: "/mnt/resources/webapps/postdata/sites/default/files/"
  #  rsync_opts:
  #    - "-avcR"
  #    - "-e ssh"
  #    - "--delete"
  #delegate_to: zoque
  #become: snaphuman
