# This playbook deploys the application stack for CMS's

- name: Apply logical volumes scheme to data disks
  hosts: prod
  roles:
    - role: data_store
      tags:
        - set_lvm

- name: apply common configuration to all nodes
  hosts: all, !localdev
  remote_user: root
  become: yes

  roles:
    - common

- name: configure the webservers
  hosts: webservers, !localdev
  remote_user: root

  roles:
    - web
    - drush

- name: configure database servers
  hosts: dbservers, !localdev
  remote_user: root

  roles:
    - db

- name: deploy applications
  hosts: webservers, !localdev
  remote_user: root
  roles:
    - role: deploy
      tags:
        - deploy

- name: sync files
  hosts: webservers, localdev
  roles: 
    - role: deploy/postdata
      tags:
        - postdata

- name: manage deployment database operations
  hosts: dbservers, !localdev, !webservers
  roles:
    - role: deploy/postdata/db
      tags:
        - postdata_db
      vars:
        - operation: "import" # use import or export"
