# This playbook deploys the application stack for CMS's

- name: Apply logical volumes scheme to data disks
  hosts: webservers, dbservers
  roles:
    - role: data_store
      tags:
        - set_lvm

- name: apply common configuration to webservers and dbservers
  hosts: webservers, dbservers, cmpt-qa-tools
  remote_user: root
  become: yes

  roles:
    - role: common
      tags:
        - common_plays

- name: configure the webservers
  hosts: webservers, !localdev
  remote_user: root

  roles:
    - role: web
      tags:
        - web_plays
    - role: drush
      tags:
        - drush_plays
    - role: web/tomcat
      tags:
        - tomcat_plays

- name: configure database servers
  hosts: dbservers, !localdev
  remote_user: root

  roles:
    - role: db
      tags:
        - db_plays
    - role: db/postgresql
      tags: 
        - postgresql_plays

- name: deploy applications means to fetch and configure
  hosts: webservers, !localdev
  remote_user: root
  roles:
    - role: deploy
      tags:
        - deploy_plays

- name: sync files and databases
  hosts: webservers, localdev
  roles: 
    - role: deploy/postdata
      tags:
        - postdata
    - role: deploy/portal_crc
      tags:
        - portal_crc
    - role: deploy/solucion_controversias
      tags:
        - solucion_controversias
    - role: deploy/dextra_reports
      tags:
        - dextra_reports
    - role: deploy/wiki_crc
      tags:
        - wiki_crc

- name: manage deployment database operations
  hosts: dbservers, !localdev, !webservers
  roles:
    - role: deploy/postdata/db
      tags:
        - postdata_db
      vars:
        - operation: "import" # use import or export"
    - role: deploy/portal_crc/db
      tags:
        - portal_crc_db
      vars:
        - operation: "import" # use import or export"
    - role: deploy/solucion_controversias/db
      tags:
        - solucion_controversias_db
      vars:
        - operation: "import" # use import or export"
    - role: deploy/wiki_crc/db
      tags:
        - wiki_crc_db
      vars:
        - operation: "import" # use import or export"

- name: enable_stats
  hosts: vm-postdata
  roles:
    - role: testing/stats
      tags:
        - enable_stats

- name: enable jmeter
  hosts: jmeter_nodes
  roles:
    - role: testing/jmeter
      tags:
        - enable_jmeter
