
- name: Importing database
  debug:
    msg: "importing {{ item.source_dump_file }} to {{ item.dbname }}"
  when: item.name == "postdata"
  with_items: "{{ applications }}"

- name: Sync files between local to remote
  shell: "rsync -avzP -e 'ssh' {{ item.source_dump_folder }}/{{ item.source_dump_file }} webmaster@{{ item.host }}:{{ temp_dir }}"
  delegate_to: "{{ item.source_host }}"
  become: snaphuman
  with_items: "{{ applications }}"
  when: item.name == "postdata"

- name: restore dump to database
  mysql_db:
    name: "{{ item.dbname }}"
    state: import
    target: /tmp/dkan-postdata-20200406.sql
  with_items: "{{ applications }}"
  when: item.name == "postdata"
